### ISSUE TITLE
metadata language field vs system language field

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/documentation#1162]
Currently the language field pulls the languages from the configured languages for the site.  It is a system property and we are using it for metadata as well.  There should be a language field for the metadata independent of the site's configured languages.  This can possibly be a controlled vocabulary: https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes, https://id.loc.gov/

**Comment by seth-shaw-unlv** [comment]
Our local content type has a language field to indicate the language of a resource, if that is what you mean:

field.field.node.dc_object.field_language.yml
```
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_language
    - node.type.dc_object
  module:
    - languagefield
id: node.dc_object.field_language
field_name: field_language
entity_type: node
bundle: dc_object
label: Language
description: "<p>A language of the resource.</p><p>If the item includes written or spoken language, select the language used.</p>"
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: language_field
```

field.storage.node.field_language.yml
```
langcode: en
status: true
dependencies:
  module:
    - field_permissions
    - languagefield
    - node
third_party_settings:
  field_permissions:
    permission_type: public
id: node.field_language
field_name: field_language
entity_type: node
type: language_field
settings:
  language_range:
    11: '11'
    1: 0
    12: 0
    2: 0
    site_default: 0
    und: 0
    current_interface: 0
    authors_default: 0
  included_languages: {  }
  excluded_languages: {  }
  groups: ''
  maxlength: 12
  allowed_values_function: languagefield_allowed_values
module: languagefield
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
```
