### ISSUE TITLE
PDF thumbnails should be PNG for transparency

### ISSUE THREAD

**Issue by kayakr** [Islandora/documentation#1260]
In my experience, JPEG thumbnails from PDFs often end up with black backgrounds.
Compare 
![2-Thumbnail Image](https://user-images.githubusercontent.com/208184/64083176-01fe0780-cd6f-11e9-8f0d-1759249e1709.jpg)
to
![ead3_output_thumbnail-0](https://user-images.githubusercontent.com/208184/64083179-15a96e00-cd6f-11e9-993a-a20879a3cf0d.png)

The latter .png was generated on the command line in the VM using
`sudo convert -thumbnail x300 -background white -alpha remove /var/www/html/drupal/EAD3_Implementation_Survey_Results_and_Discussion_20190320.pdf ead3_output_thumbnail.png`

I assume the way to do this is to clone action 'Image - Generate a thumbnail from an original file', change `mimetype` to `image/png` and alter the contexts so that the original 'Image - Generate a thumbnail from an original file' action only applies to model=Image, while the new action applies when model=Document?

**Comment by dannylamb** [comment]
Yep, that's totally how it would work. And I can also attest that I've seen
black backgrounds from generated jpegs in the past. :+1: Good suggestion.

**Comment by kayakr** [comment]
`web/modules/contrib/islandora_defaults/config/install/system.action.digital_document_generate_a_thumbnail_from_an_original_file.yml`

```yaml
langcode: en
status: true
dependencies:
  module:
    - islandora_image
id: digital_document_generate_a_thumbnail_from_an_original_file
label: 'Digital Document - Generate a thumbnail from an original file'
type: node
plugin: generate_image_derivative
configuration:
  queue: islandora-connector-houdini
  event: 'Generate Derivative'
  source_term_uri: 'http://pcdm.org/use#OriginalFile'
  derivative_term_uri: 'http://pcdm.org/use#ThumbnailImage'
  mimetype: image/png
  args: '-thumbnail 100x100'
  destination_media_type: image
  scheme: public
  path: '[date:custom:Y]-[date:custom:m]/[node:nid]-[term:name].png'
```
This is working for me, manually via admin/content. Next we need to tweak contexts.
