### ISSUE TITLE
We should expose taxonomy terms' external URIs to Views

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1311]
There's a chance I'm not using Views correctly, but I'd like to create a View with a REST endpoint that allows me to get all the nodes that have a tag with a specific external URI, e.g. for the Binary model:

`curl -vi "http://localhost:8000/islandora_model?_format=json&model=http://purl.org/coar/resource_type/c_1843"`

I want to be able to query a bunch of Islandoras using the same parameter rather than site-specific term IDs. If I can query on external URIs, I can do neat stuff like show a block that has "related items" in other Islandora repos. Linked Data FTW!

Here is the Filter Criteria settings for the Content: Model filter in my View:

![view](https://user-images.githubusercontent.com/403918/66969141-41da2f00-f03d-11e9-8b67-c12429fb5286.png)

I'm attaching the YAML of the View I'm playing with. To use it, you'll need to paste it into `http://localhost:8000/admin/config/development/configuration/single/import` after selecting "View" from the Configuration Type select list. After that, "Islandora Model" should show up in your list of Views.

[islandora_model_view.yml.txt](https://github.com/Islandora/documentation/files/3736950/islandora_model_view.yml.txt)

**Comment by dannylamb** [comment]
@mjordan I had to do just the same thing recently.  You use a 'relationship' to make the fields of the taxonomy term available, and then you can make a filter based on `field_external_uri`.  Here's an example of how we get Preservation Master files.  It's for Media, but the same technique would apply to Nodes: http://localhost:8000/admin/structure/views/view/display_media?destination=/admin/structure/views

![image](https://user-images.githubusercontent.com/20773151/67009565-4c8ad780-f0c2-11e9-8514-355655efc0d6.png)

The relationship is in advanced, and you'd set that based on `field_model ` instead of `field_media_use`.  Then you'd filter on the model term's external uri as a string instead of using term ids.

**Comment by mjordan** [comment]
@dannylamb sweet, I'll give this a whirl. My spidy sense tells me that we should have a whole section of our cookbook devoted to advanced Views.....

**Comment by mjordan** [comment]
Or to accompany a set of cookbook entries, we could create a set of gists/wiki pages/etc. collecting YAML configs so people could paste in preconfigured Views.

**Comment by mjordan** [comment]
Got this to work. Thanks @dannylamb for revealing the magician's secret: registering the target taxonomy as a Relationship, which exposes the uri for use in the filter. Now the following request returns objects that are tagged with the "Binary" model:

`http://localhost:8000/islandora_model?_format=json&uri=http://purl.org/coar/resource_type/c_1843`

and this request returns objects that are tagged with the "Image" model:

`http://localhost:8000/islandora_model?_format=json&uri=http://purl.org/coar/resource_type/c_c513`

Here's the configuration dump of my View:

```
uuid: 2e7255a0-f3cb-4f96-b53b-ad7c7519805c
langcode: en
status: true
dependencies:
  module:
    - node
    - rest
    - serialization
    - taxonomy
    - user
id: islandora_model
label: 'Islandora Model'
module: views
description: ''
tag: ''
base_table: node_field_data
base_field: nid
core: 8.x
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      access:
        type: perm
        options:
          perm: 'access content'
      cache:
        type: tag
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: mini
        options:
          items_per_page: 10
          offset: 0
          id: 0
          total_pages: null
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      style:
        type: serializer
      row:
        type: fields
        options:
          inline: {  }
          separator: ''
          hide_empty: false
          default_field_elements: true
      fields:
        title:
          id: title
          table: node_field_data
          field: title
          entity_type: node
          entity_field: title
          label: ''
          alter:
            alter_text: false
            make_link: false
            absolute: false
            trim: false
            word_boundary: false
            ellipsis: false
            strip_tags: false
            html: false
          hide_empty: false
          empty_zero: false
          settings:
            link_to_entity: true
          plugin_id: field
          relationship: none
          group_type: group
          admin_label: ''
          exclude: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_alter_empty: true
          click_sort_column: value
          type: string
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      filters:
        status:
          value: '1'
          table: node_field_data
          field: status
          plugin_id: boolean
          entity_type: node
          entity_field: status
          id: status
          expose:
            operator: ''
          group: 1
        field_external_uri_uri:
          id: field_external_uri_uri
          table: taxonomy_term__field_external_uri
          field: field_external_uri_uri
          relationship: field_model
          group_type: group
          admin_label: ''
          operator: '='
          value: ''
          group: 1
          exposed: true
          expose:
            operator_id: field_external_uri_uri_op
            label: 'External URI (field_external_uri:uri)'
            description: ''
            use_operator: false
            operator: field_external_uri_uri_op
            identifier: uri
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              administrator: '0'
              fedoraadmin: '0'
            placeholder: ''
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          plugin_id: string
      sorts: {  }
      header: {  }
      footer: {  }
      empty: {  }
      relationships:
        field_model:
          id: field_model
          table: node__field_model
          field: field_model
          plugin_id: standard
      arguments: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - request_format
        - url
        - url.query_args
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
  rest_export_1:
    display_plugin: rest_export
    id: rest_export_1
    display_title: 'REST export'
    position: 1
    display_options:
      display_extenders: {  }
      path: islandora_model
      pager:
        type: some
        options:
          items_per_page: 10
          offset: 0
      style:
        type: serializer
        options:
          grouping: {  }
          uses_fields: false
          formats: {  }
      row:
        type: data_entity
        options: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - request_format
        - url
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
```
