### ISSUE TITLE
Is it possible to migrate files of different media types using the same migration config?

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/documentation#1397]
The migration example is hard coding the file type or the mime type: https://github.com/Islandora/migrate_islandora_csv/blob/dev/config/install/migrate_plus.migration.file.yml#L75

Is it possible to migrate set of files with different media or mime types?

**Comment by seth-shaw-unlv** [comment]
Short answer is yes. Your source data needs to have something your config can use to identify which media type it should be, but it can be done. 

E.g. I have one migration that includes JPGs, TIFFs, and PDFs; I migrate them all using the same config. I can share examples, but I need to head to a meeting right now.

**Comment by Natkeeran** [comment]
@seth-shaw-unlv thanks

**Comment by Natkeeran** [comment]
Do file names need to be unique?  Otherwise, it seems to be overwritting!

**Comment by seth-shaw-unlv** [comment]
Here is a trimmed down version of what we are doing with some added comments sprinkled in...
```
source:
  plugin: csv
  path: modules/local_migrations/metadata/neon_files_test.tsv
  delimiter: "\t"
  header_row_count: 1
  keys:
    - file_path
  constants:
    uid: 1
  column_names: # I removed some columns that aren't relevant to this ticket....
    -
      digital_id: 'Digital Identifier' # This field is used to look up what repository_object the media belongs to.
    -
      file_path: Path # File path to where the file currently lives
    -
      media_use_uris: 'Media Use URIs' # URI of Original File, Service File, etc... we have several objects where we've already generated derivatives and we can include them all in this spreadsheet source.

process:
  bundle: # This determines which Media Type we are creating (file, image, audio, etc.).
    -
      plugin: substr # First we grab the file extension. This isn't bullet proof, but was good enough for our set because everything with a non-three-character extension will be a File Media anyway.
      source: file_path
      start: -3
      length: 3
    -
      plugin: callback # Both 'JPG' and 'jpg' extensions become 'jpg'
      callable: strtolower
    -
      plugin: static_map # A map between extensions (left side) and the media type (right side)
      map:
        jpg: image
        tif: file # Drupal considers Tiffs files because most browsers can't display them natively.
        pdf: file
      default_value: file
  uid: constants/uid
  # We define mappings for BOTH field_media_image and field_media_file in this migration but we skip filling out the irrelevant one for a particular media by using the skip_on_value plugin. 
  field_media_image/target_id:
    -
      plugin: skip_on_value # Only populate the field_media_image/target_id IF we already determined that the bundle is 'image'.
      source: '@bundle'
      not_equals: TRUE
      value: image
      method: process
    -
      plugin: migration_lookup
      migration: neon_files
      source: file_path
      no_stub: true
  field_media_image/display:
    -
      plugin: skip_on_value
      source: '@bundle'
      not_equals: TRUE
      value: image
      method: process
    -
      plugin: default_value
      default_value: 1
  field_media_image/description:
    -
      plugin: skip_on_value
      source: '@bundle'
      not_equals: TRUE
      value: image
      method: process
    -
      plugin: default_value
      default_value: ''  
  # Repeating the same pattern as field_media_image above.
  field_media_file/target_id:
    -
      plugin: skip_on_value
      source: '@bundle'
      not_equals: TRUE
      value: file
      method: process
    -
      plugin: migration_lookup
      migration: neon_files
      source: file_path
      no_stub: true
  field_media_file/display:
    -
      plugin: skip_on_value
      source: '@bundle'
      not_equals: TRUE
      value: file
      method: process
    -
      plugin: default_value
      default_value: 1
  field_media_file/description:
    -
      plugin: skip_on_value
      source: '@bundle'
      not_equals: TRUE
      value: file
      method: process
    -
      plugin: default_value
      default_value: ''
  field_media_of:
    plugin: migration_lookup
    migration: neon_metadata
    source: digital_id
    no_stub: true
  field_media_use: # Defines the Media Use of this media
    -
      plugin: explode # We support multiple media use URIs delimited by semi-colons. E.g. BOTH OriginalFile and ServiceFile for PDFs.
      delimiter: ;
      source: media_use_uris
    -
      plugin: entity_lookup
      value_key: field_external_uri
      bundle_key: vid
      bundle: islandora_media_use
      entity_type: taxonomy_term
      ignore_case: true
destination:
  plugin: 'entity:media'
migration_dependencies:
  optional: # Making them optional means files and metadata will run first, but won't complain if those migrations skipped some records.
    - neon_files
    - neon_metadata
```

As for the file names question, which comes into play with the file migration; file names themselves do not need to be unique, but the paths do. We use the file's original path (sans any common mount-point directories) with a collection prefix to keep it unique.
