### ISSUE TITLE
We no longer need to install python on Ubuntu 18.04

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1403]
Ubuntu 18.04 ships with python 3, so instead of installing python 2, we can set `ansible_python_interpreter=/usr/bin/python3` in our host file if using Ubuntu.

**Comment by whikloj** [comment]
We still allow people to specify other versions so we should either restrict the base boxes allowed or make the check of ubuntu versions decide on this action.

**Comment by dannylamb** [comment]
Eureka:

In `bootstrap.yml` we do this to ensure python
```yml
    - name: install python
      raw: test -e /usr/bin/python || (apt-get update; apt-get install -y python;)
      register: output
      changed_when:
        - output.stdout != ""
        - output.stdout != "\r\n"
      when: islandora_distro|default('') is match("ubuntu/")
```
which leads to it being skipped when the playbook is run
```
TASK [install python] ************************************************************************************************************************
Wednesday 22 January 2020  15:19:30 -0400 (0:00:00.078)       0:00:00.078 ***** 
skipping: [default]
```
because I'm running `ansible-playbook` manually and not using Vagrant, so `islandora_distro` is not defined :sweat_smile:  

I'll confirm by adding that in with `-e` next time I cycle these boxes.
