### ISSUE TITLE
Config in `islandora_defaults` has enforced dependency on `islandora_core_feature`

### ISSUE THREAD

**Issue by dannylamb** [Islandora/documentation#1478]
All the config has

```yml
  enforced:
    module:
      - islandora_core_feature
```

which would make it uninstall if you uninstall `islandora_core_feature`.  Feels like we should be removing this config when `islandora_defaults` is uninstalled.
