### ISSUE TITLE
'rdau' RDF namespace is not registered

### ISSUE THREAD

**Issue by mjordan** [Islandora/documentation#1520]
`config/install/rdf.mapping.node.islandora_object.yml` defines the following mapping:

```
  field_edition:
    properties:
      - 'rdau:P60329'
```

but the `rdau` namespace is not registered (or at least isn't known to the `rdf_get_namespaces()` function). Should we add that namespace to `islandora_rdf_namespaces()`?

I think `rdau` is used as the namespace for http://www.rdaregistry.info/, but I can't find P60329 in any of the ontologies registered there. Metadata IG folks, any suggestions?

**Comment by whikloj** [comment]
Perhaps also `co`?
https://github.com/Islandora/islandora_defaults/blob/8.x-1.x/config/install/rdf.mapping.node.islandora_object.yml#L106

**Comment by whikloj** [comment]
Nevermind, `co` is defined in core islandora

**Comment by mjordan** [comment]
Maybe we should do a review to see if all the namespaces for all the default mappings are registered?

**Comment by seth-shaw-unlv** [comment]
Maybe we should finally just make this namespace thing configurable....

**Note: this is untested code... just something that popped into mind and written up real quick.**

rdf_map.schema.yml
```
rdf_map:
    type: config_object
    mapping:
        rdf_mappings:
            type: sequence
            label: 'RDF Mappings'
            sequence:
                type: mapping
                mapping:
                    prefix: 
                        type: string
                        label: 'RDF Prefix'
                    namespace:
                        type: string
                        label: 'Fully Qualified RDF Namespace'
```

rdf_map.yml
```
rdf_mappings:
    -
        prefix: 'ldp'
        namespace: 'http://www.w3.org/ns/ldp#',
    -
        prefix: 'dc11'
        namespace: 'http://purl.org/dc/elements/1.1/',
    -
        prefix: 'dcterms'
        namespace: 'http://purl.org/dc/terms/',
    -
        prefix: 'nfo'
        namespace: 'http://www.semanticdesktop.org/ontologies/2007/03/22/nfo/v1.1/',
    -
        prefix: 'ebucore'
        namespace: 'http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#',
    -
        prefix: 'fedora'
        namespace: 'http://fedora.info/definitions/v4/repository#',
    -
        prefix: 'owl'
        namespace: 'http://www.w3.org/2002/07/owl#',
    -
        prefix: 'ore'
        namespace: 'http://www.openarchives.org/ore/terms/',
    -
        prefix: 'rdf'
        namespace: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    -
        prefix: 'rdau'
        namespace: 'http://rdaregistry.info/Elements/u/'
    -
        prefix: 'islandora'
        namespace: 'http://islandora.ca/',
    -
        prefix: 'pcdm'
        namespace: 'http://pcdm.org/models#',
    -
        prefix: 'use'
        namespace: 'http://pcdm.org/use#',
    -
        prefix: 'iana'
        namespace: 'http://www.iana.org/assignments/relation/',
    -
        prefix: 'premis'
        namespace: 'http://www.loc.gov/premis/rdf/v1#',
    -
        prefix: 'premis3'
        namespace: 'http://www.loc.gov/premis/rdf/v3/',
    -
        prefix: 'co'
        namespace: 'http://purl.org/co/',
```

islandora.module
```
/**
 * Implements hook_rdf_namespaces().
 */
function islandora_rdf_namespaces() {
    
    $rdf_map_config = \Drupal::config('rdf_map');
    $rdf_mappings = $rdf_map_config->get('rdf_mappings');
    if (!is_array($rdf_mappings)) {
      throw new \Exception("RDF Map config is not an array.");
    }
    $maps = [];
    foreach ($rdf_mappings as $rdf_map) {
      $maps[$rdf_map['prefix'] = $rdf_map['namespace'];
    }
  
  return $maps;
}
```

This is, of course, less efficient that simply returning a hard-coded list, but much easier for sites to update; especially with Features. Also, I recently learned that we can add weight to our module so it's module file is processed after others, making it more likely that our config will override other mappings set.
