### ISSUE TITLE
Playbook fails when installing on Centos 7 where selunx is disabled

### ISSUE THREAD

**Issue by ainsofs** [Islandora/documentation#1556]
I get the following error:

```
fatal: [default]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ sestatus_out.stdout|regex_search('Current mode.*(permissive|enforcing)')|regex_search('(permissive|enforcing)') }}): expected string or buffer"}
```

I am installing using ansible to a dev environment with selinux is turned off where sestatus_out.stdout value is below

```
ok: [default] => {
    "sestatus_out.stdout": "SELinux status:                 disabled\r\n"
}
```

updating bootstrap.yml to below worked for me

```
    # Parse sestatus down to one of two options.
    - name: Set selinux permissive fact
      set_fact:
        # selinux_permissive: "{{ sestatus_out.stdout|regex_search('Current mode.*(permissive|enforcing)')|regex_search('(permissive|enforcing)') }}"
        selinux_permissive: "disabled"
      when: ansible_os_family == "RedHat"
```
