### ISSUE TITLE
Create Fedora DB (mysql) fails when deploying to remote machine

### ISSUE THREAD

**Issue by ruebot** [Islandora/documentation#1631]
Setup:
*  Following instructions as outlined [here](https://islandora.github.io/documentation/installation/playbook/#installing-a-remote-environment)
* `ansible-galaxy install -r requirements.yml`
* `ansible-playbook -i inventory/yudl8 playbook.yml -e "islandora_distro=ubuntu/bionic64" --extra-vars "ansible_sudo_pass=some_password"`

TASK [Islandora-Devops.fcrepo : Create Fedora DB (mysql) fails

```
fatal: [default]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"}
```

**Comment by ruebot** [comment]
I ended up removing `login_host`, `login_port`, `login_user`, and `login_password`. Basically, similar to the approach in [ansible-role-matomo](https://github.com/Islandora-Devops/ansible-role-matomo/blob/main/tasks/db-mysql.yml).

In the end what worked for me was:

```yml
- name: Create Fedora DB (mysql)
  mysql_db:
    name: "{{ fcrepo_db_name }}"
    state: present
  register: fcrepo_db_exists

- name: Create Fedora DB User (mysql)
  mysql_user:
    name: "{{ fcrepo_db_user }}"
    password: "{{ fcrepo_db_password }}"
    state: present
    priv: "{{fcrepo_db_name}}.*:ALL"
```

If y'all want a PR for this, I can take care of it. Just let me know. Or the current approach is the preferred approach, was can just close this issue, and it can serve as gotcha documentation for anybody using the playbook for remote installs.
