### ISSUE TITLE
linkFieldPassthrough broken

### ISSUE THREAD

**Issue by elizoller** [Islandora/documentation#1773]
I spun up a new playbook install of islandora and created objects using migrate_islandora_csv. Then I chose one of the items and added a resource type from the pre-populated options that were provided by islandora_defaults. Then I viewed the oai_dc stream and was able to see
```
<dc:type>Image</dc:type>
```
as part of the output.

Then I modified the rdf.mapping.node.islandora_object.yml following the instructions here: http://islandora.github.io/documentation/islandora/rdf-mapping/#datatype-callbacks
like so:
```
  field_resource_type:
    properties:
      - 'dcterms:type'
    mapping_type: rel
    datatype_callback:
      callable: 'Drupal\jsonld\EntityReferenceConverter::linkFieldPassthrough'
      arguments:
        link_field: 'field_authority_link'
```
My understanding is that this should provide the URI from the field_authority_link if one is available. If not, it should still provide the string value.

After importing the config, I'm getting no value at all in the dc:type
```
<dc:type/>
```
