### ISSUE TITLE
Ansible Playbook can spin up both Standard and Demo Install Profile 

### ISSUE THREAD

**Issue by alxp** [Islandora/documentation#1993]
PR: https://github.com/Islandora-Devops/islandora-playbook/pull/206

By specifying in either a Unix environment variable or Ansible inventory variable, a user can use the Playbook to spin up either a vanilla Drupal site with Islandora Defaults enabled or the islandora_install_profile_demo Install Profile.

**Comment by misilot** [comment]
Is the `islandora_install_profile_demo` or `demo` the same as the install profile that one would get with isle-dc?

**Comment by alxp** [comment]
Here's the Ansible variables pertaining to the 'demo' option:

```yaml
cmtctest:islandora-playbook aoneill$ cd vars/
cmtctest:vars aoneill$ cat demo.yml 
---

drupal_build_composer_project: false

drupal_deploy: true
drupal_build_composer: false
drupal_deploy_repo: https://github.com/islandora-devops/islandora-sandbox
drupal_deploy_version: install-profile
drupal_deploy_dir: "{{ drupal_composer_install_dir }}"
drupal_deploy_update: yes
drupal_deploy_composer_install: yes
drupal_deploy_accept_hostkey: yes

drupal_install_profile: islandora_install_profile_demo
openseadragon_composer_item: "islandora/openseadragon:^2"
```
So they should be the same if you set the environment variable $ISLANDORA_INSTALL_PROFILE to 'demo'.
